openapi: 3.0.3
info:
  title: Stelsel metadata & Dienstcatalogus API
  version: 1.0.0-SNAPSHOT

paths:
  /authenticatiediensten:
    get:
      tags:
        - Authenticatiediensten
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/AuthenticatieDienst'
    post:
      tags:
        - Authenticatiediensten
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticatieDienst'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/AuthenticatieDienst'
    delete:
      tags:
        - Authenticatiediensten
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticatieDienst'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/AuthenticatieDienst'
  /dienstverlener:
    get:
      tags:
        - Dienstverleners
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/Dienstverlener'
    post:
      tags:
        - Dienstverleners
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dienstverlener'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/Dienstverlener'
    delete:
      tags:
        - Dienstverleners
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dienstverlener'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: '#/components/schemas/Dienstverlener'
components:
  schemas:
    AuthenticatieDienst:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    Dienstverlener:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
